#!/bin/bash

# ==============================================================================
# Auto-Installer for Service Monitoring and Auto-Restart Script
#
# This script automates the creation and setup of a monitoring script
# that checks a service's logs for a specific warning and restarts it
# if the warning is found.
# ==============================================================================

# --- Configuration ---
LOG_PATTERN="channel is full"
SCRIPT_INSTALL_PATH="/usr/local/bin"
# --- End Configuration ---


# Function to print colored output
print_status() {
    echo -e "\e[34m[INFO]\e[0m $1"
}

print_success() {
    echo -e "\e[32m[SUCCESS]\e[0m $1"
}

print_error() {
    echo -e "\e[31m[ERROR]\e[0m $1"
}

# 1. Check for root privileges
check_root() {
    if [[ $EUID -ne 0 ]]; then
        print_error "This script must be run as root. Please use sudo."
        exit 1
    fi
}

# 2. Get and validate user input
get_user_input() {
    # Get the original user who ran sudo
    ACTUAL_USER=${SUDO_USER:-$(whoami)}

    # Get Service Name
    while true; do
        read -p "Enter the systemd service name to monitor (e.g., iran123.service): " SERVICE_NAME
        if systemctl list-unit-files --type=service | grep -q "^${SERVICE_NAME}$"; then
            break
        else
            print_error "Service '${SERVICE_NAME}' not found. Please check the name and try again."
        fi
    done

    # Get Execution Time
    while true; do
        read -p "Enter the execution interval in minutes (e.g., 5 for every 5 minutes): " EXECUTION_TIME
        if [[ "$EXECUTION_TIME" =~ ^[0-9]+$ ]] && [ "$EXECUTION_TIME" -gt 0 ]; then
            break
        else
            print_error "Invalid time. Please enter a positive integer."
        fi
    done
}

# 3. Create the monitoring script
create_monitor_script() {
    MONITOR_SCRIPT_FILENAME="restart_on_full_${SERVICE_NAME//./_}.sh"
    MONITOR_SCRIPT_PATH="${SCRIPT_INSTALL_PATH}/${MONITOR_SCRIPT_FILENAME}"

    print_status "Creating monitoring script at ${MONITOR_SCRIPT_PATH}..."

    # Use a heredoc to write the script content
    cat << EOF > "$MONITOR_SCRIPT_PATH"
#!/bin/bash

# This script was automatically generated by setup_monitor.sh
# It monitors the '${SERVICE_NAME}' service for the pattern '${LOG_PATTERN}'.

SERVICE="${SERVICE_NAME}"
PATTERN="${LOG_PATTERN}"

# Check logs in the last 10 minutes for the warning pattern
if /usr/bin/journalctl -u "\$SERVICE" --since "10 minutes ago" | /usr/bin/grep -q "\$PATTERN"; then
    /usr/bin/logger "WARNING: '\$PATTERN' detected for \$SERVICE. Restarting service."
    /usr/bin/sudo /usr/bin/systemctl restart "\$SERVICE"
fi
EOF

    chmod +x "$MONITOR_SCRIPT_PATH"
    if [ $? -eq 0 ]; then
        print_success "Monitoring script created and made executable."
    else
        print_error "Failed to create or set permissions for the monitoring script."
        exit 1
    fi
}

# 4. Configure sudoers for passwordless restart
setup_sudoers() {
    SUDOERS_FILE="/etc/sudoers.d/monitoring_${SERVICE_NAME//./_}"

    print_status "Configuring sudoers for passwordless restart at ${SUDOERS_FILE}..."

    # Create the sudoers entry
    echo "${ACTUAL_USER} ALL=(ALL) NOPASSWD: /bin/systemctl restart ${SERVICE_NAME}" > "$SUDOERS_FILE"

    # Set correct permissions for the sudoers file
    chmod 0440 "$SUDOERS_FILE"

    if [ $? -eq 0 ]; then
        print_success "Sudoers rule added successfully."
    else
        print_error "Failed to configure sudoers. Please check permissions on /etc/sudoers.d/."
        exit 1
    fi
}

# 5. Add the cron job
setup_cron() {
    CRON_JOB="*/${EXECUTION_TIME} * * * * ${MONITOR_SCRIPT_PATH}"
    TEMP_CRON_FILE=$(mktemp)

    print_status "Adding cron job for user '${ACTUAL_USER}' to run every ${EXECUTION_TIME} minutes..."

    # Get existing crontab and check if our job already exists
    (crontab -u "$ACTUAL_USER" -l 2>/dev/null | grep -v -F "$MONITOR_SCRIPT_PATH"; echo "$CRON_JOB") > "$TEMP_CRON_FILE"

    # Install the new crontab
    crontab -u "$ACTUAL_USER" "$TEMP_CRON_FILE"
    rm "$TEMP_CRON_FILE"

    if [ $? -eq 0 ]; then
        print_success "Cron job added successfully."
    else
        print_error "Failed to add cron job."
        exit 1
    fi
}

# --- Main Execution ---
main() {
    print_status "Starting automated setup..."
    check_root
    get_user_input
    create_monitor_script
    setup_sudoers
    setup_cron

    echo "------------------------------------------------------------"
    print_success "Setup complete!"
    echo " - Service to monitor: ${SERVICE_NAME}"
    echo " - Monitoring script: ${MONITOR_SCRIPT_PATH}"
    echo " - Cron interval: Every ${EXECUTION_TIME} minutes"
    echo " - The script will now run automatically in the background."
    echo "------------------------------------------------------------"
}

main
